# Generated by Django 2.2.6 on 2019-11-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20191114_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[(1, 'Phone'), (2, 'FACEBOOK'), (3, 'EMAIL')], max_length=10),
        ),
    ]
